seedChoiceClones=False
seedChannelClones='ROI Mask'
invertSeedClones=True
minSeedSizeClones=50.0
subAdd=0.0
borderMargin=8.0
holeDiameter=20.0
rollingZ=0
winwo=False
DBSCANChoice='Flood + Fill Holes'
DBSCANminDensityOE=3
DBSCANdistOE=50.0
DBSCANminCellsInCluster=10.0
DBSCANmode='Disabled'
DBSCANminDensity=3
DBSCANdist=22.0
clonesPost='None'
blurClones=0.0
