seedChoiceClones=False
seedChannelClones='0'
invertSeedClones=True
minSeedSizeClones=50.0
subAdd=0.0
borderMargin=1e+24
holeDiameter=20.0
rollingZ=0
winwo=False
DBSCANChoice='Flood + Fill Holes'
DBSCANminDensityOE=4
DBSCANdistOE=62.0
DBSCANminCellsInCluster=200.0
DBSCANmode='Disabled'
DBSCANminDensity=3
DBSCANdist=22.0
clonesPost='Dilate, close, erode'
blurClones=0.0
