zMethod='Disabled'
ROIseg='Manual Selections'
restoreROI=False
ROIchannel='1r'
cloneSeg='Use ROIs As Clones'
numGenotypes=2
cloneChannel='3g'
singleCellMethod='Disabled'
cellCount=False
DAPIchannel=1
cellCountChannel='3g'
cellDeathSegMethod='Default'
dcp1Choice=True
preProcess='None'
dcp1Channel='3r'
fluoChannel='2g'
speckleMethod='Disabled'
speckleChannel=2
frame_interval=1
cloneTracking=False
dcp1Counting=False
cellCountDeluxe=True
dcp1Deluxe=False
fluoChoice=False
speckle=False
timelapse=False
minCloneSize=15.0
speckleNoise=100.0
