seedChoiceClones=False
seedChannelClones='ROI Mask'
invertSeedClones=True
minSeedSizeClones=50.0
subAdd=25.0
borderMargin=8.0
holeDiameter=10.0
rollingZ=0
winwo=False
DBSCANmode='Disabled'
DBSCANminDensity=3
DBSCANdist=22.0
clonesPost='Despeckle'
blurClones=0.0
