zMethod='Disabled'
ROIseg='Manual Selections'
restoreROI=True
ROIchannel='2g'
cloneSeg='Membrane-tagged GFP'
numGenotypes=1
cloneChannel='2g'
singleCellMethod='Disabled'
cellCount=False
DAPIchannel=1
cellCountChannel='2g'
cellDeathSegMethod='Default'
dcp1Choice=True
preProcess='None'
dcp1Channel='3r'
fluoChannel='2'
speckleMethod='Disabled'
speckleChannel=2
frame_interval=1
cloneTracking=False
dcp1Counting=False
fluoChoice=True
speckle=False
timelapse=False
minCloneSize=15.0
speckleNoise=100.0
